<?php  
  
session_start(); 
  
// To check if session is started. 
if(isset($_SESSION["employee"]["id"]))  
{ 
    if(time()-$_SESSION["login_time_stamp"] >5000)   
    { 
        session_unset(); 
        session_destroy(); 
        header("Location: home.php"); 
    } 
} 
else
{ }

?> 


<!DOCTYPE html>
<html lang="en" dir="ltr">
 <head>
    <meta charset="utf-8">
     <title>Travelchec Dashboard</title>
     <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-2/css/all.min.css">
    <link href="css/sweetalert.css" rel="stylesheet">
    <style type="text/css">
      #message {
        display:none;
        background: #f1f1f1;
        color: #000;
        position: relative;
        padding: 20px;
        margin-top: 10px;
      }
            /* Add a green text color and a checkmark when the requirements are right */
      .valid {
        color: green;
      }

      .valid:before {
        position: relative;
        left: -35px;
        content: "✔";
      }

      /* Add a red text color and an "x" when the requirements are wrong */
      .invalid {
        color: red;
      }

      .invalid:before {
        position: relative;
        left: -35px;
        content: "✖";
      }
      td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
      }
      table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
      }
      </style>
 </head>   
<body>
    
    <input type="checkbox" id="check">


<!--header area start-->    
<header>
    <label for="check">
        <i class="fas fa-bars" id="sidebar_btn"></i>
    </label>
    <div class="left_area">
        <h3>Travel<span>Chec</span></h3>
    </div>
    <div class="right_area">
  <?php
     if (isset($_SESSION['employee']['id'])) { ?>
        <a href="logout.php" class="logout_btn">Logout</a>
     <?php } else { ?>
     
     <?php }
  ?>
    </div>
</header>
<!--header area end-->


<!--Sidebar included-->   
<?php include 'sidebar_emp.php'; ?>


<!--Script to change login-->  
<?php
include 'inc/config.php';

if (count($_POST) > 0) {
    
    $login_emp_id = $_SESSION['employee']['id'];
    $newpassword = $_POST['newpassword'];

    if ($_POST["newpassword"] == $_POST["confirmpassword"]) {
        mysqli_query($conn, "UPDATE employee_details set password='".md5($newpassword)."' WHERE id='" . $login_emp_id . "'");

    } else
        $error = "<p style='color: red;'>Both Password does not match</p>";
}
?>



<!--Main content area started--> 
<div class="content">
  <div class="content-body"><br><br>
    <h1>Dashboard</h1>

    <h2><label id="lblGreetings"></label><?php echo $_SESSION['employee']['name']; ?></h2><br>

    <?php
       include 'inc/config.php';
       $login_id = $_SESSION['employee']['id'];
       $password = 'password';
       $select_password = mysqli_query($conn, "SELECT * FROM employee_details WHERE id = '$login_id' AND password='".md5($password)."'");
       $prow = mysqli_fetch_assoc($select_password);


       if (mysqli_num_rows($select_password) == 1) { ?>
        <h4>"You are trying to access the system using a password generated by system"</h4>
        <h5>Change password below</h5>

<?php if(isset($error)){ echo $error; }?>


<form name="frmChange" method="post" action="" >

<div class="box-row">
  <div class="box-column">
      <div style="width:500px;">          
        <table border="0" cellpadding="10" cellspacing="0" width="500" align="center" class="tblSaveForm">
          <tr class="tableheader">
          </tr>

          <tr>
            <td><label>New Password: </label></td>
            <td>
            <div class="first-example">
            <input type="password" id="psw" name="newpassword" pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}" title="Must contain at least one number and one uppercase and lowercase letter, and at least 8 or more characters" required></span> <i id="pass-status" class="fa fa-eye" aria-hidden="true" onClick="viewPassword()"></i>
            </div>
          </td>
          </tr>
          <tr>
          <td><label>Confirm Password: </label></td>
          <td><input type="password" name="confirmpassword" class="txtField" required/></td>
          </tr>
          <tr>
          <td colspan="2"><input type="submit" name="change" value="Change Password" class="password"></td>
          </tr>
        </table>             
        </div>
  </div>


  <div class="box-column">
      <div id="message">
        <h3>Password must contain the following:</h3>
          <p id="letter" class="invalid">A <b>lowercase</b> letter</p>
          <p id="capital" class="invalid">A <b>capital (uppercase)</b> letter</p>
          <p id="number" class="invalid">A <b>number</b></p>
          <p id="length" class="invalid">Minimum <b>8 characters</b></p>
      </div>
  </div>
</div>
 </form>



    <?php   } else { ?>

  <?php
    $login_emp = $_SESSION['employee']['id'];
    $selectmv = mysqli_query($conn, "SELECT mv.status, mv.id as mvid, mv.model, md.id, md.name as modl, my.id, mv.year, my.year as yea, m.id, m.name, mv.emp_id, mv.EngineNo, e.id, e.first_name, e.last_name, mv.make, mv.model, mv.year, mv.ChassisNo
  FROM motor_vehicle mv
  JOIN employee_details e on mv.emp_id = e.id
  JOIN makes m on mv.make = m.id
  JOIN make_years my on mv.year = my.id
  JOIN models md on mv.model = md.id 
  WHERE mv.emp_id = '$login_emp' 
  ORDER BY mv.status ASC ");
    $row = mysqli_fetch_assoc($selectmv);
    if (mysqli_num_rows($selectmv) == 0) { ?>
 
    <a class="btn btn-primary" href="add_motor_vehicle.php">Add Motor vechicle</a>

  <?php  } else { ?>

    <?php
      $select_doc_stat = mysqli_query($conn, "SELECT * FROM motor_vehicle_document WHERE mv_id = ".$row['mvid']." ");
      $drow = mysqli_fetch_assoc($select_doc_stat);

    ?>

  <h3>Motor Vechicle Document Status</h3>
  <table>
  <tr>
    <th>Name</th>
    <th>Motor Vechicle</th>
    <th>Licence</th>
    <th>Registration</th>
    <th>Fitness</th>
    <th>Insurance</th>
    <th>Status</th>
  </tr>
  <tr>
    <td><?php echo $row['last_name']; ?>, <?php echo $row['first_name']; ?></td>
    <td><?php echo $row['yea']; ?>, <?php echo $row['name']; ?> <?php echo $row['modl']; ?></td>
    <td>
      <?php
      if (empty($drow['licence_class']) && empty($drow['licence_trn']) && empty($drow['licence_date_issued']) && empty($drow['licence_date_expired']) && empty($drow['licence_sex'])) { ?>
       <a style="color: red; text-align: center; font-size: 25px;" ><i class="fas fa-times-circle"></i></a> 
       <?php  } else { ?>
          <i style="color: green; text-align: center; font-size: 25px;" class="fas fa-check-circle"></i>
      <?php }
      ?>
    </td>
    <td>
     <?php
      if (empty($drow['registration_vehicle_type']) && empty($drow['registration_fee']) && empty($drow['registration_mfg_type']) && empty($drow['registration_laden_weight']) && empty($drow['registration_plate_no'])) { ?>
       <a style="color: red; text-align: center; font-size: 25px;" ><i class="fas fa-times-circle"></i></a> 
       <?php  } else { ?>
          <i style="color: green; text-align: center; font-size: 25px;" class="fas fa-check-circle"></i>
      <?php }
      ?>
    </td>
    <td>
      <?php
      if (empty($drow['fitness_issue_date']) && empty($drow['fitness_expiry_date']) && empty($drow['fitness_od_meter_reading']) && empty($drow['fitness_traffic_authority']) && empty($drow['fitness_spermit_no'])) { ?>
       <a style="color: red; text-align: center; font-size: 25px; " ><i class="fas fa-times-circle"></i></a> 
       <?php  } else { ?>
          <i style="color: green; text-align: center; font-size: 25px;" class="fas fa-check-circle"></i>
      <?php }
      ?>
    </td>
    <td>
      <?php
      if (empty($drow['insurance_company']) && empty($drow['insurance_policy_holder']) && empty($drow['insurance_start_date']) && empty($drow['insurance_expiry_date']) && empty($drow['insurance_classes'])) { ?>
       <a style="color: red; text-align: center; font-size: 25px;" ><i class="fas fa-times-circle"></i></a> 
       <?php  } else { ?>
          <i style="color: green; text-align: center; font-size: 25px;" class="fas fa-check-circle"></i>
      <?php }
      ?>
    </td>
    <td><a class="btn btn-primary" href="add_motor_vehicle_document.php?eid=<?php echo $row['emp_id']; ?>">Submit Document</a></td>
  </tr>
  
</table>
      
  <?php  }



  ?>
















   <?php    }
     ?>




 
    </div>
</div>
<!--Main content area end--> 
<script src="js/jquery/jquery.min.js"></script>
<script src="js/jquery/jquery-migrate.min.js"></script>
<script src="js/sweetalert.js"></script>
<script type="text/javascript">
  function viewPassword()
  {
    var passwordInput = document.getElementById('psw');
    var passStatus = document.getElementById('pass-status');
   
    if (passwordInput.type == 'password'){
      passwordInput.type='text';
      passStatus.className='fa fa-eye-slash';
      
    }
    else{
      passwordInput.type='password';
      passStatus.className='fa fa-eye';
    }
  }
</script>
<script>
var myInput = document.getElementById("psw");
var letter = document.getElementById("letter");
var capital = document.getElementById("capital");
var number = document.getElementById("number");
var length = document.getElementById("length");

// When the user clicks on the password field, show the message box
myInput.onfocus = function() {
  document.getElementById("message").style.display = "block";
}

// When the user clicks outside of the password field, hide the message box
myInput.onblur = function() {
  document.getElementById("message").style.display = "none";
}

// When the user starts to type something inside the password field
myInput.onkeyup = function() {
  // Validate lowercase letters
  var lowerCaseLetters = /[a-z]/g;
  if(myInput.value.match(lowerCaseLetters)) {  
    letter.classList.remove("invalid");
    letter.classList.add("valid");
  } else {
    letter.classList.remove("valid");
    letter.classList.add("invalid");
  }
  
  // Validate capital letters
  var upperCaseLetters = /[A-Z]/g;
  if(myInput.value.match(upperCaseLetters)) {  
    capital.classList.remove("invalid");
    capital.classList.add("valid");
  } else {
    capital.classList.remove("valid");
    capital.classList.add("invalid");
  }

  // Validate numbers
  var numbers = /[0-9]/g;
  if(myInput.value.match(numbers)) {  
    number.classList.remove("invalid");
    number.classList.add("valid");
  } else {
    number.classList.remove("valid");
    number.classList.add("invalid");
  }
  
  // Validate length
  if(myInput.value.length >= 8) {
    length.classList.remove("invalid");
    length.classList.add("valid");
  } else {
    length.classList.remove("valid");
    length.classList.add("invalid");
  }
}
</script>

    
<script>
    var myDate = new Date();
    var hrs = myDate.getHours();

    var greet;

    if (hrs < 12)
        greet = 'Good Morning!';
    else if (hrs >= 12 && hrs <= 17)
        greet = 'Good Afternoon!';
    else if (hrs >= 17 && hrs <= 24)
        greet = 'Good Evening!';

    document.getElementById('lblGreetings').innerHTML =
        '' + greet + ' ';
</script>     
    
</body>
</html>
     
     
